package:
  name: zbox
  version: "1.2.0"

source:
  fn: zbox-1.2.0.tar.gz
  url: https://pypi.python.org/packages/source/z/zbox/zbox-1.2.0.tar.gz
  md5: faa2f3104736e00c5c937da5835b3391
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - zbox = zbox:main
    #
    # Would create an entry point called zbox that calls zbox.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cytoolz >=0.7.0

  run:
    - python
    - cytoolz >=0.7.0

test:
  # Python imports
  imports:
    - zbox

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jiffyclub/zbox
  license: ISC License (ISCL)
  summary: "Get cytoolz or toolz, whatever's around"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
